### ISSUE TITLE
Add possibility to change IC

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#20]
Default to 95.

Add choice to  : 

- [x] multivarié
- [x] croisement deux à deux

**Comment by DrFabach** [comment]
Où est-ce qu'on ajoute le choix de l'IC ?avant le modèle où on laisse le choix après que le modèle ait tourné ?

**Comment by severacf** [comment]
Avant !

De : DrFabach ***@***.***>
Envoyé : mercredi 9 août 2023 19:28
À : GMRC-HUS/ShiBA ***@***.***>
Cc : SEVERAC Francois ***@***.***>; Assign ***@***.***>
Objet : Re: [GMRC-HUS/ShiBA] Add possibility to change IC (Issue #20)


Où est-ce qu'on ajoute le choix de l'IC ?avant le modèle où on laisse le choix après que le modèle ait tourné ?
