### ISSUE TITLE
Verifier les fonctions pour les variables ayant des données manquantes

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#39]

**Comment by Bineta14** [comment]
![image](https://github.com/GMRC-HUS/ShiBA/assets/75995403/06a24741-f550-4c5a-96bf-cf811bb7e0f4)

**Comment by DrFabach** [comment]
ça ne marche pas du coup

**Comment by Bineta14** [comment]
Non pas pour le modèle de Poisson

**Comment by Bineta14** [comment]
Thibaut,

Nicolas aussi a le même problème avec la régression de poisson.

J'ai corrigé le problème (c'était pas grand chose)  poussé les commits sur ma branche, pourrais-tu regarder et fusionner?

**Comment by DrFabach** [comment]
Commit fusionné
