### ISSUE TITLE
define default prior

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#7]

**Comment by severacf** [comment]
On laisse les priors par défaut de rstanarm

**Comment by DrFabach** [comment]
Oui mais c'est lesquels ?

**Comment by severacf** [comment]
Ils s'ajustent aux données
En reg lin, pour l'intercept, c'est une normale (mean(y), 2.5*sd(y))
Pour les coeff, c'est une normale (0, (2.5/sd(x))*sd(y))
Pour sigma, c'est une exponentielle (1/sd(y))

**Comment by DrFabach** [comment]
Default prior defined
