### ISSUE TITLE
Variables modèles multivarié

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#71]
Lors du changement de type de modèle, les variables restent présente dans les boites en dessous.

Il faut rendre réactifs ces boites pour qu'elles se réinitialisent quand le type de modèle est changé.

**Comment by Bineta14** [comment]
Si j' ai bien compris, les cases **Variables  quantitatives** et **Variables qualitatives** doivent être  vide à chaque fois qu'on change de type de modèle.

**Comment by Bineta14** [comment]
En cours

**Comment by Bineta14** [comment]
Me semble ok aussi...
