### ISSUE TITLE
Pb lors du choix d'un seuil uniques lors de la comparaison de plusieurs groupes

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#72]
Dans l'onglet comparaison de moyenne, lorsqu'on mais le même seuil pour l'ensemble des groupes, le résultats n'est pas correct.

**Comment by Bineta14** [comment]
Je regarderai...

**Comment by Bineta14** [comment]
Réglé

**Comment by DrFabach** [comment]
Tu n'as pas fait de commit ?

**Comment by Bineta14** [comment]
Si je pousserai les modifs…

**Comment by Bineta14** [comment]
Me semble ok

**Comment by DrFabach** [comment]
Tu as mergé du coup?

**Comment by Bineta14** [comment]
J'ai tout poussé sur la branche 73, donc normalement c'est ok.
