### ISSUE TITLE
Implement 2i and threshold in result

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#8]

**Comment by severacf** [comment]
## Threshold
# Modèle
model_1 = stan_glm(kid_score ~ mom_hs, family = gaussian(link = "identity"),
                   data = kidiq, refresh = 0)

# Seuils et fonction

seuil=c(75,8) # 1 = intercept
res<-sapply(1:(length(model_1$stanfit@sim$fnames_oi)-3), 
       function(i) length(which(as.array(model_1)[,,i]>seuil[i]))/length(as.array(model_1)[,,i]))
Pr<-c(res,NA,NA)

# Présentation des résultats
tab<-tidyMCMC(model_1$stanfit, conf.int = TRUE, conf.level = 0.95, 
              robust=TRUE, rhat=TRUE, ess=TRUE)	
tab2<-cbind(tab,Pr)
knitr::kable(tab2[-(dim(tab)[1]-1),],digits = 3,
             align=c("l","c", "c", "c", "c", "c", "c", "c"), row.names = FALSE)

**Comment by severacf** [comment]
## 2IT et threshold (fonctionne avec une reg lin avec la variable groupe du 2IT en première variable explicative du modèle)

Cp2moyStan2IT <- function(mod,seuild=NULL,HAdl=NULL,HAdu=NULL,
                          HPdl=NULL,HPdu=NULL,arr=3,
						  M=length(as.array(mod)[,,2]),
						  diff=as.array(mod)[,,2]){
  
  Sim=100000
  loc=prior_summary(mod)$prior$location[1]
  scale=prior_summary(mod)$prior$adjusted_scale[1]  
  if(is.null(prior_summary(mod)$prior$adjusted_scale)){
  scale=prior_summary(mod)$prior$scale[1]} 
  diffprior<-rnorm(Sim,loc,scale)
  
  respdi<-matrix(NA,nrow=5,ncol=1)
  rownames(respdi)<-c(paste("HA : Pr(",HAdl," < diff < ",HAdu,") ="),
                      paste("HP : Pr(",HPdl," < diff < ",HPdu,") ="),
                      paste("HA | D : Pr(",HAdl," < diff < ",HAdu," | D) ="),
                      paste("HP | D : Pr(",HPdl," < diff < ",HPdu," | D) ="),
                      "Pr(différence > seuil diff | D) =")

  colnames(respdi)<-"" 

  if(is.null(seuild)){respdi<-NULL}else{
    respdi[1,1] <- round(sum(diffprior>(HAdl) & diffprior<(HAdu))/Sim,arr)
    respdi[2,1] <- round(sum(diffprior>(HPdl) & diffprior<(HPdu))/Sim,arr)
    respdi[3,1] <- round(sum(diff>(HAdl) & diff<(HAdu))/M,arr)
    respdi[4,1] <- round(sum(diff>(HPdl) & diff<(HPdu))/M,arr)
    respdi[5,1] <- round(sum(diff>seuild)/M,arr)
  }  

  return(respdi)

}

**Comment by severacf** [comment]
C’est bon ça !!

De : DrFabach ***@***.***>
Envoyé : mercredi 26 juillet 2023 18:09
À : GMRC-HUS/ShiBA ***@***.***>
Cc : SEVERAC Francois ***@***.***>; Assign ***@***.***>
Objet : Re: [GMRC-HUS/ShiBA] Implement 2i and threshold in result (Issue #8)


Closed #8<https://github.com/GMRC-HUS/ShiBA/issues/8> as completed.
