### ISSUE TITLE
Add convergence check

### ISSUE THREAD

**Issue by DrFabach** [GMRC-HUS/ShiBA#9]
- [x] Il faut rajouter un test sur les autocorrelation : 
@severacf  Comment tu extrait les autocorrelation d'un fit de rstanarm ?

- [x] Ajout de la loop si convergence non ok .

**Comment by severacf** [comment]
## Modèle
model_1 = stan_glm(kid_score ~ mom_hs, family = gaussian(link = "identity"),
                   data = kidiq, refresh = 0)

## extraction AC
s = as.array(model_1)
mcmc <- do.call(mcmc.list, plyr:::alply(s[, , -(length(s[1, 1, ]))], 2, as.mcmc))
autocorr.diag(mcmc, lags = c(1:50))->AC

## test
is.element("TRUE", AC>0.2)
